name: 🐍 Snake Animation
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🎮 Render contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: Ash-D3v
          outputs: |
            dist/snake.svg?color_snake=#ff6ac1&color_dots=#0d1117,#0e4429,#006d32,#26a641,#39d353
      - name: 🚀 Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
